### PR TITLE
Bump up ruby and gems

### PR DESCRIPTION
**Pull request by gauravtiwari**
## What did we change?

Bump up Rails and ruby versions

## Why are we doing this?

To bring compatibility for Rails 6

## How was it tested?
- [x] Specs
- [x] Locally
- [ ] Staging

### CODE REVIEW

**Comment by tjwp** [comment]
Thanks for the contribution. It looks like our ezcater_rubocop gem may need to be updated to a newer version that supports ruby 2.6. I'll look at doing that and then this can be rebased.

**Comment by gauravtiwari** [comment]
Thanks, Tim, just reverted it back to 2.5. Perhaps, best to do the ruby change in another PR once you have `ezcater_rubocop` updated

**Comment by gauravtiwari** [comment]
CI test reporter is failing:

```
Coverage report generated for RSpec to /home/circleci/ezcater/coverage. 53 / 54 LOC (98.15%) covered.
Error: response from https://api.codeclimate.com/v1/test_reports.
HTTP 401: You are not authorized for this action
Usage:
  cc-test-reporter after-build [flags]
```

**Comment by tjwp** [comment]
No, I ran tests on another branch and it correctly submitted the coverage. Perhaps it is restricting to members of our Github org?

I don't think there is anything more you need to do here. I'm happy that the tests are passing with the exception of the coverage. Do you need a release cut so that you can test in combination with other things?

> CI test reporter is failing:
> 
> ```
> Coverage report generated for RSpec to /home/circleci/ezcater/coverage. 53 / 54 LOC (98.15%) covered.
> Error: response from https://api.codeclimate.com/v1/test_reports.
> HTTP 401: You are not authorized for this action
> Usage:
>   cc-test-reporter after-build [flags]
> ```
> 
> Any idea, why?

**Comment by gauravtiwari** [comment]
Great, yes please if you can cut a new release that would be amazing, thank you 🙏

**Comment by tjwp** [comment]
@gauravtiwari you should be all set with v1.1.0

**Pull request merged**
